// Copyright (c) 2013 Arista Networks, Inc.  All rights reserved.
// Arista Networks, Inc. Confidential and Proprietary.

#include <EosSdk/version.h>
#include "config.h"  // Generated by configure

const char * const version = PACKAGE_VERSION;
