#!/usr/bin/env python
# Copyright (c) 2013 Arista Networks, Inc.  All rights reserved.
# Arista Networks, Inc. Confidential and Proprietary.

""" Implements a simple Echo bot script. This script does not handle
write errors as EchoBot.cpp does. """

import eossdk

import socket
import sys

ECHO_MSG = "You said: "
LISTEN_PORT = 10000
IDLE_TIMEOUT = 10
LISTEN_BACKLOG = 5
MAX_BUF_SIZE = 1024

class EchoBot(eossdk.TimeoutHandler, eossdk.FdHandler):
   def __init__(self, timeoutMgr):
      print "initializing..."
      eossdk.TimeoutHandler.__init__(self, timeoutMgr)
      eossdk.FdHandler.__init__(self)  # pylint: disable-msg=W0233
      self.server = self._createServer()
      self.watch_readable(self.server.fileno(), True)
      self.connectedSocket = None
      print "initialized with server=%d" % self.server.fileno()

   def on_readable(self, fd):
      print "onReadable called"
      if fd == self.server.fileno():
         assert not self.connectedSocket, ("Should not be readable if we "
                                           "already have a connection")
         self._acceptConnection()
      elif fd == self.connectedSocket.fileno():  # pylint: disable-msg=E1101
         data = self.connectedSocket.recv(MAX_BUF_SIZE -
                                          len(ECHO_MSG)) # pylint: disable-msg=E1101
         print "Client said: %r" % data
         if not data:
            self._endConnection()
            return
         self.connectedSocket.send(ECHO_MSG + data)  # pylint: disable-msg=E1101
         self.timeout_time_is(eossdk.now() + IDLE_TIMEOUT)
      else:
         assert False, "Unknown fd %d is readable" % fd

   def on_timeout(self):
      print "Timer called"
      assert self.connectedSocket
      self._endConnection()

   def _acceptConnection(self):
      print "Accepting connection"
      assert not self.connectedSocket
      self.watch_readable(self.server.fileno(), False)
      newFd, _ = self.server.accept()
      newFd.setblocking(0)  # pylint: disable-msg=E1101
      self.connectedSocket = newFd
      self.watch_readable(newFd.fileno(), True)  # pylint: disable-msg=E1101
      self.timeout_time_is(eossdk.now() + IDLE_TIMEOUT)

   def _endConnection(self):
      fd = self.connectedSocket.fileno()  # pylint: disable-msg=E1101
      print "end connection to connected socket %d" % fd
      self.watch_readable(fd, False)
      self.connectedSocket.close()
      self.connectedSocket = None
      # Start listening for new connections again
      self.watch_readable(self.server.fileno(), True)
      self.timeout_time_is(eossdk.never)

   def _createServer(self):
      print "Creating server"
      s = socket.socket()
      s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
      s.setblocking(0)
      s.bind(("", LISTEN_PORT))
      s.listen(LISTEN_BACKLOG)
      return s

sdk = eossdk.Sdk()
echoBot = EchoBot(sdk.get_timeout_mgr())
sdk.main_loop("EchoBotPy", sys.argv)
