/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef EosThrift_CONSTANTS_H
#define EosThrift_CONSTANTS_H

#include "EosThrift_types.h"

namespace eos {

class EosThriftConstants {
 public:
  EosThriftConstants();

};

extern const EosThriftConstants g_EosThrift_constants;

} // namespace

#endif
