/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "EosThrift_constants.h"

namespace eos {

const EosThriftConstants g_EosThrift_constants;

EosThriftConstants::EosThriftConstants() {
}

} // namespace

