/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "EosThrift_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace eos {

int _kOperStatusValues[] = {
  OperStatus::UNKNOWN,
  OperStatus::UP,
  OperStatus::DOWN
};
const char* _kOperStatusNames[] = {
  "UNKNOWN",
  "UP",
  "DOWN"
};
const std::map<int, const char*> _OperStatus_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(3, _kOperStatusValues, _kOperStatusNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

int _kInterfaceTypeValues[] = {
  InterfaceType::UNKNOWN,
  InterfaceType::OTHER,
  InterfaceType::ETH,
  InterfaceType::VLAN,
  InterfaceType::MANAGEMENT,
  InterfaceType::LOOPBACK,
  InterfaceType::LAG,
  InterfaceType::NULL0
};
const char* _kInterfaceTypeNames[] = {
  "UNKNOWN",
  "OTHER",
  "ETH",
  "VLAN",
  "MANAGEMENT",
  "LOOPBACK",
  "LAG",
  "NULL0"
};
const std::map<int, const char*> _InterfaceType_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(8, _kInterfaceTypeValues, _kInterfaceTypeNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

} // namespace
